### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by ghost** [CityOfZion/neochat#3]
Setup CI for code quality and testing.

Elixir: default elixir test framework and credo.
JS: will probably follow [this](https://medium.com/@eliotjunior/prettier-eslint-facebook-code-quality-the-auto-magical-react-styling-tutorial-19481acb10dd) but opened to suggestions
- ~~Setup travis~~
- ~~Setup elixir code quality~~
- ~~Setup elixir tests ~~
- ~~Setup JS code quality~~
- ~~Setup JS tests~~

**Comment by steffenix** [comment]
CI setup for travis in #4

**Comment by ghost** [comment]
Changes in:
https://github.com/CityOfZion/neochat/commit/45fb6aae3e967c03ea9c454d63bb83bee8cab030
https://github.com/CityOfZion/neochat/commit/562046c79a79d2d1768fd43666380a7f6bcba8cd
https://github.com/CityOfZion/neochat/commit/6503e25d424a6fe4fcc37041eb6616f95c937b81
https://github.com/CityOfZion/neochat/pull/6
